# Generated by Django 3.2.9 on 2021-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0005_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
