# Generated by Django 3.2.9 on 2021-12-11 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0006_alter_customeuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customeuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='college_management.customeuser')),
                ('year', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management.department')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('college_management.customeuser',),
        ),
    ]
