# Generated by Django 3.2.9 on 2021-12-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0009_notification_accountant_notification_faculty_notification_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_accountant',
            name='accountant',
        ),
        migrations.RemoveField(
            model_name='notification_faculty',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='notification_student',
            name='student',
        ),
    ]
