# Generated by Django 3.2.9 on 2021-12-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0010_auto_20211225_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whome', models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student'), ('Accountant', 'Accountant')], max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification_accountant',
        ),
        migrations.DeleteModel(
            name='Notification_faculty',
        ),
        migrations.DeleteModel(
            name='Notification_student',
        ),
    ]
