# Generated by Django 3.2.9 on 2021-12-25 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0013_notification_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
