# Generated by Django 3.2.9 on 2021-12-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0014_alter_notification_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Book_name', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='whome',
            field=models.CharField(choices=[('All', 'All'), ('Faculty', 'Faculty'), ('Student', 'Student'), ('Accountant', 'Accountant'), ('Librarian', 'Librarian')], max_length=10),
        ),
        migrations.CreateModel(
            name='Assign_book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_date', models.DateField()),
                ('due_date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management.add_book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management.student')),
            ],
        ),
    ]
