# Generated by Django 3.2.9 on 2021-12-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0017_alter_assign_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_mark', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management.subject')),
            ],
        ),
    ]
