# Generated by Django 3.2.9 on 2022-01-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0022_alter_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='status',
        ),
    ]
