# Generated by Django 4.0.2 on 2022-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0031_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_book',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
