# Generated by Django 4.0.2 on 2022-02-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0032_alter_add_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_book',
            name='status',
            field=models.CharField(choices=[('assign', 'assign'), ('recieve', 'recieve')], max_length=100),
        ),
    ]
